### ISSUE TITLE
Test on Amazom Cluster

### ISSUE THREAD

**Issue by arita297** [lacava/ellen#2]
This is a good project.
Just wondering if you have test it on Amazon Cluster EC2.

What about multiple clusters ?

Is there a way to do Paralell Island ?

**Comment by lacava** [comment]
the islands option will parallelize the population across cores on one node. the RunTrialsMPI executable can submit multiple runs across nodes on a cluster with MPI integration; most linux clusters with LSF job schedulers support that. I have not tried it on EC2, but it should work with the right VM setup. 

I would also point you to github.com/EpistasisLab/ellyn, an implementation of ellen with a python wrapper.

**Comment by arita297** [comment]
Hello,

Thanks for details.
Just for reference, do you have some benchmark tests (comparing with DEAP GP one) ?

2) In term of expression complexity, how much increase in compute time (1CPU) for one level of tree depth ?


This is a good project, will look into the details.

Kind regards
Arita






On 17 Dec 2016, at 04:38, William La Cava <notifications@github.com> wrote:

the islands option will parallelize the population across cores on one node. the RunTrialsMPI executable can submit multiple runs across nodes on a cluster with MPI integration; most linux clusters with LSF job schedulers support that. I have not tried it on EC2, but it should work with the right VM setup.

I would also point you to github.com/EpistasisLab/ellyn, an implementation of ellen with a python wrapper.

―

**Comment by lacava** [comment]
1) i haven't benchmarked against DEAP. Generally, I would expect ellen to be much faster given the c++ implementation. They have some overlap in terms of algorithms implemented. 
2) the programs are linear in ellen, and length limits can be tuned to the number of nodes rather than expression depth. the notion of complexity with tree depth is a bit mismatched here since ellen uses a stack-based execution strategy, in which instructions push and pull data from typed stacks rather than being evaluated recursively which is usually the case with tree-based gp. you should expect a computational efficiency on the order of 10^7 - 10^8 node evaluations per second, context dependent.

a number of papers have tested the complexity of ellen experimentally, including:
http://www.sciencedirect.com/science/article/pii/S0952197616301294
http://williamlacava.com/pubs/GECCO_lex_reg-corrected.pdf

comprehensive tests are in my dissertation:
http://scholarworks.umass.edu/dissertations_2/731/

**Comment by arita37** [comment]
Thanks for you references,
Just wondering if Ellen can be used for more general kind of elementary node function like :  
```
   def mynode_fun(x,y) : 
       ..... 
       return val
```

where myfun can be wrapped in python or C++ ?


2) Just for the usage, where can we define the Terminal Set of elementary functions ?

Thanks, Cheers
Arita

**Comment by lacava** [comment]
ellen could be used with self-defined functions. unfortunately it is not very simple to implement your own. first the function would need to be included in Fitness.cpp and referenced in the eval() function. then it would need to be included in the node creation functions which are somewhat spread out among the source code, generally in variation and initialization stages.

the existing operators can be defined using the 'op_list' parameter. for example, this would use constants (n), variables (v), and the mathematical operators with default weights:
```op_list				n	v	+	-	*	/	sin	cos	exp	log```
the full set of operators are
```n	v	+	-	*	/	sin	cos	exp	log sqrt ^ = ! < > <= >= if-then if-then-else & |```

edit: myfun would have to be written in c++ for use in ellen. with some development it could be included as a python function by [ellyn](http://github.com/EpistasisLab/ellyn).

**Comment by arita37** [comment]
Hello,

Thanks for details.
One idea coming from having own function is to reduce the computationnal 
space by 're-normalizing' into
'custom function'  (ie  PCA in functionnal space).

For example, instead of having Polynomial base like  ( 1, x, x**2, x**3, 
...),
we can think of having another base  (1, myFun, myFun**2, MyFun).

Think Ellen would greatly benefit to increase computational fit and 
handle more complex problems,
by having a way to define custom function in an easier way.

Adding the benefits, that user can bring own 'customized functions' for 
his domain area.

What would you think ?

Thanks, regards.
Kevin





William La Cava wrote:

**Comment by lacava** [comment]
I think it's a neat idea to have user-defined functions. I don't intend to develop them myself but I would encourage others to do so. My viewpoint with GP is that it should be used to develop these functions, rather than having them made by hand. That said, using the correct operators for the domain is essential. In fact, my main project now (github.com/lacava/few) is based around using GP to find functional transformations from the original data to a new space as a wrapper for other ML methods. That might interest you. Good luck!
